### ISSUE TITLE
 CRITICAL Uncaught Error 

### ISSUE THREAD

**Issue by gine** [LDAV/woocommerce-pdf-italian-add-on#10]
I getted this error after payed with paypal on a sandbox:

2018-07-15T00:38:44+00:00 CRITICAL Uncaught Error: Call to a member function get_value() on string in /home/gasmyotxpb/www/wp-content/plugins/woocommerce-pdf-invoices-italian-add-on/woocommerce-pdf-italian-add-on.php:247
Stack trace:
#0 /home/gasmyotxpb/www/wp-includes/class-wp-hook.php(286): WooCommerce_Italian_add_on->after_order_notes('')
#1 /home/gasmyotxpb/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/gasmyotxpb/www/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/gasmyotxpb/www/wp-content/plugins/um-woocommerce/core/um-woocommerce-api.php(83): do_action('woocommerce_aft...')
#4 /home/gasmyotxpb/www/wp-content/plugins/um-woocommerce/core/filters/um-woocommerce-account.php(227): UM_WooCommerce_Core->edit_address(Array)
#5 /home/gasmyotxpb/www/wp-includes/class-wp-hook.php(286): um_account_content_hook_billing(NULL)
#6 /home/gasmyotxpb/www/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array)
#7 /home/gasmyotxpb/www/wp-content/plugins/ultimate-member/core/um-account.php(248): ap

**Comment by w3b-beweb** [comment]
Same here
